project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Katie Burak"

  page-footer:
    left: "&copy; Copyright 2026, Katie Burak"
    right: "Built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: docked
    collapse-level: 1
    contents:
      - text: "Projects"
        href: projects/index.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "Courses"
        href: courses.qmd
      - text: "Publications"
        href: publications.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    smooth-scroll: true

