project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Katie Burak"

  page-footer:
    left: "&copy; Copyright 2024, Katie Burak"
    right: "This page is built with [Quarto](https://quarto.org/)."

  sidebar:
    pinned: true
    align: center
    style: "docked"
    collapse-level: 1
    contents:

      - text: "Projects"
        href: projects/index.qmd

      - text: "Talks"
        href: talks/index.qmd

      - text: "Courses"
        href: courses.qmd
      
      - text: "Publications"
        href: publications.qmd

#      - section: "About"
#        contents:
#          - text: "About me"
#            href: about.qmd
#          - text: "This template"
#            href: about_template.qmd


format:
  html:
    css: styles.css
    toc: true


