---
title: "Diversity in Data Science: Empowering Women Through Outreach"
description: "IDWSDS Conference 2024"
date: "2024-10-08"
link: https://www.youtube.com/watch?v=Ztliu7ehAk8
---

### Abstract

In 2024, the Data Science Council of America reported that although 57% of women make up the overall workforce, only 27% of employees in the technology industry are women. We are currently still facing the challenge of insufficient representation of women and other gender minorities in data science and statistics. However, it is has been observed that perhaps this gender imbalance may start from a much earlier point than when individuals are entering the workforce. The "leaky pipeline" is a term that describes the phenomenon of the loss of women in STEM fields , despite them having strong abilities and interest in these domains. To help overcome systemic barriers that women face in these industries, I believe it is important that we impact students early on to expose them to new topics and perhaps inspire them to pursue careers in data science. In this talk, I will discuss my experiences with data science outreach and how engaging our communities can promote future women in the field.

[Click here](https://www.youtube.com/watch?v=Ztliu7ehAk8) to watch a recording of this talk on YouTube. 